[workspace]
members = [
    "crypto",
    "network-hypervisor",
    "controller",
    "service",
    "vl1-service",
    "utils",
]

[profile.release]
opt-level = 3
strip = true
debug = false
codegen-units = 1
lto = true
