[package]
name = "zerotier-core-crypto"
version = "0.1.0"
edition = "2018"
license = "MPL-2.0"
authors = ["ZeroTier, Inc. <contact@zerotier.com>", "Adam Ierymenko <adam.ierymenko@zerotier.com>"]

[dependencies]
rand_core = "0.5"
aes-gmac-siv = { path = "../aes-gmac-siv" }
gcrypt = "0.7.0"
x25519-dalek = { version = "1.2.0", features = ["u64_backend"] }
ed25519-dalek = { version = "1.0.1", features = ["u64_backend"] }
