on: [ push ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: gitconfig
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: checkout
      uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
        override: true
        components: rustfmt, clippy

    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: make
      run: make
    - name: selftest
      run: make selftest

  # build_macos:
  #   runs-on: macos-latest
  #   steps:
  #   - name: gitconfig
  #     run: |
  #       git config --global core.autocrlf false
  #       git config --global core.eol lf
  #   - name: checkout
  #     uses: actions/checkout@v3
  #   - name: Install Rust
  #     uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #       target: aarch64-apple-darwin
  #       override: true
  #       components: rustfmt, clippy
  #   - name: Set up cargo cache
  #     uses: actions/cache@v3
  #     continue-on-error: false
  #     with:
  #       path: |
  #         ~/.cargo/bin/
  #         ~/.cargo/registry/index/
  #         ~/.cargo/registry/cache/
  #         ~/.cargo/git/db/
  #         target/
  #       key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  #       restore-keys: ${{ runner.os }}-cargo-
  #   - name: Lint
  #     run: |
  #       cargo fmt --all -- --check
  #       cargo clippy -- -D warnings
  #   - name: make
  #     run: make
  #   - name: selftest
  #     run: make selftest

  # build_windows:
  #   runs-on: windows-latest
  #   steps:
  #   - name: gitconfig
  #     run: |
  #       git config --global core.autocrlf false
  #       git config --global core.eol lf
  #   - name: checkout
  #     uses: actions/checkout@v3
  #   - name: Install Rust
  #     uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #       target: aarch64-apple-darwin
  #       override: true
  #       components: rustfmt, clippy
  #   - name: Set up cargo cache
  #     uses: actions/cache@v3
  #     continue-on-error: false
  #     with:
  #       path: |
  #         ~/.cargo/bin/
  #         ~/.cargo/registry/index/
  #         ~/.cargo/registry/cache/
  #         ~/.cargo/git/db/
  #         target/
  #       key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  #       restore-keys: ${{ runner.os }}-cargo-
  #   - name: Lint
  #     run: |
  #       cargo fmt --all -- --check
  #       cargo clippy -- -D warnings
  #   - name: setup msbuild
  #     uses: microsoft/setup-msbuild@v1.1.3
  #   - name: msbuild
  #     run: |
  #       msbuild windows\ZeroTierOne.sln /m /p:Configuration=Release  /property:Platform=x64 /t:ZeroTierOne:Rebuild
